[build-system]
requires = [
    "setuptools>=62.0.0,<75.0.0",
    "wheel>=0.37.0",
    "pybind11>=3.0.0",
    "numpy>=2.2.6"
]
build-backend = "setuptools.build_meta"

[project]
name = "daisy-exact-search"
version = "1.0.0"
description = "DaiSy: A Library for Scalable Data Series Similarity Search"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Franscesca Del Gaudio"},
    {name = "Manos Chatzakis"},
    {name = "Gayathiri Ravendirane"},
    {name = "Themis Palpanas"},
]
keywords = ["similarity-search", "data-series"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers", 
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows", 
    "Programming Language :: C++",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "numpy>=2.2.6",
    "pybind11>=3.0.0",
    "mpi4py>=4.0.3",
]

[project.optional-dependencies]
dev = [
    "build>=1.0.0",
    "cmake>=3.15",
    "pip>=24.0.0",
    "pytest>=7.0.0",
    "setuptools>=80.9.0",
    "twine>=4.0.0",
    "wheel>=0.45.1",
]

[project.urls]
Homepage = "https://github.com/MChatzakis/DaiSy"
Repository = "https://github.com/MChatzakis/DaiSy"
Issues = "https://github.com/MChatzakis/DaiSy/issues"

[tool.setuptools]
packages = []

[tool.wheel]
universal = false
